### ISSUE TITLE
Partition manager doesn't start after clicking on edit partition button.

### ISSUE THREAD

**Issue by FredBezies** [endeavouros-team/liveuser-desktop-settings#2]
I noticed I had to run partitionmanager from a terminal in order to get it working. I saw this on a 30 minutes old github based ISO.

Good old gparted was working flawlessly before.

**Comment by killajoe** [comment]
Thanks, we do remove gparted, as having to partitions managers is looking strange, partitionmanager is what calamares is needing so we add this to the launcher but he seem to do not like it...

**Comment by Portergos** [comment]
I forgot to add the fix some days ago, sorry about that, and thanks for reminding me. 

Explanation: partitionmanager need to be started as normal user, since my last change was trying to use sudo just like gparted, it just didn't launch. 

Not sure though if ask for a password when the user tries some change; since the liveuser can run sudo without password can't see a popup window. 

Gparted on the other hand ask password to start, so it used sudo command to startup.
